FROM node:lts

WORKDIR /app

VOLUME [ "/logs" ]

#COPY ./src /app

RUN npm install --save react @apollo/client
#RUN <install all dependencies>

#ENV <environment variables...>
#ENV <environment variables...>

CMD ["node", "/app/"]
#CMD ["node", "/app/frontend"]
#CMD ["/bin/bash"]  # for troubleshooting inside container